exclude: ^scientific_survey/migrations/
repos:
-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
        args:
            - --in-place
            - --remove-all-unused-imports
            - --expand-star-imports
            - --remove-duplicate-keys
            - --remove-unused-variables
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
    -   id: flake8
        args: [--config=.flake8]
